spring:
  application:
    name: "Talk Nest Social Application"
    port: 8080

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/talknestdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

google:
  email:
    from:
      username: ${FROM_SENDER:kag40222@gmail.com}
      application-key: ${APPLICATION_KEY:riko jnde suam hima}
      port: ${FROM_PORT:587}

